name: extended_logger
description: A logger api with some convenience stuff for better logging.
version: 0.2.3
repository: https://github.com/martinsellergren/extended_logger

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.0.0
  stack_trace: ^1.0.0
  talker: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.4
  test: ^1.24.0
